### ISSUE TITLE
file was generated by an older version of protoc

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#17]
Hi 
I tried to build the project, but while building i get below error in genfiles\tensorflow\core\framework\step_stats.pb.h .

#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

Please help resolving it. My GOOGLE_PROTOBUF_MIN_PROTOC_VERSION is defined as
 #define GOOGLE_PROTOBUF_MIN_PROTOC_VERSION 3003000  

in include/google/protobuf/stubs/common.h which I have downloaded from https://github.com/google/protobuf/tree/master/src/google/protobuf as 
https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/49125122ca1db5720b8be2d8cefbafdbc3ec4010/jni-build/jni/include/google/protobuf didn't had folders or required files

**Comment by sladomic** [comment]
Hi

At the moment it's cumbersome to build the native libs, that's why I will change to using the recently announced official Jcenter library of TensorFlow. If you really want to build it, you can try this https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/issues/1

This worked for me to upgrade TF to the latest release. Bit as mentioned it's not straightforward.

**Comment by ashokbugude** [comment]
Thanks, I shall look into it and try. Closing the issue, Please update me in case you are able to implement it
Thanks

**Comment by ashokbugude** [comment]
Able to build by following the steps in above link. Thanks for your help

**Comment by sladomic** [comment]
I just implemented the easy way (Jcenter library of TensorFlow). But at the moment it fails to load huge neural networks (like the one with 580Mb). So I can't commit it right now..
