### ISSUE TITLE
Location of built tensorflow.so Library

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#20]

**Comment by sladomic** [comment]
@ashokbugude what is the question exactly and which version of the library do you use?

**Comment by ashokbugude** [comment]
Can I please know the location where the libtensorflow.so library file be
built when we build the project

On Jun 3, 2017 12:58 PM, "sladomic" <notifications@github.com> wrote:

@ashokbugude <https://github.com/ashokbugude> what is the question exactly
and which version of the library do you use?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/issues/20#issuecomment-305958114>,
or mute the thread

**Comment by sladomic** [comment]
@ashokbugude In the old version, where you couldbuild from source (the one you are using, I suppose), you can find the libs here https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/v1.4.0/jni-build/libs if you execute the make command in the jni-build folder. The command make install then copies these libs to /src/main/jniLibs

But I don't know your setup, because you've changed a lot of things. Best would be that you fork the library, apply your changes and commit them to your fork. So I could see your changes on your GitHub fork

**Comment by ashokbugude** [comment]
Thanks for your response. Yes I am speaking about old version and I assume I have not made any modifications to your older version. Can I please know how are the  libs in https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/v1.4.0/jni-build/libs generated? Are these generated from Android.mk file when we build the project ? 
Will the make command be automatically executed when we build the Android project or do we need to run manually everytime we build the project ?

**Comment by sladomic** [comment]
When we first started the project this was executed automatically but we separated it one day because we wanted to have control of which lib version we use. So now it's a manual execution. It shouldn't be so difficult to include it. You would need to add some config to the gradle files, but I don't know the exact config anymore

**Comment by ashokbugude** [comment]
Thanks, 
Sorry to ask you again, I couldn't understand the answer for below question 

Can I please know how are the libs in https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Library/tree/v1.4.0/jni-build/libs generated?

**Comment by sladomic** [comment]
They are generated with ndk-build, which is provided by the Android NDK. It uses the jni/Application.mk and jni/Android.mk files as config files, then executes the toolchain compiler https://developer.android.com/ndk/guides/ndk-build.html https://developer.android.com/ndk/guides/standalone_toolchain.html

**Comment by ashokbugude** [comment]
Thanks, 
 to run the ndk-build provided by Android NDK, I need to run the make file right ? As the ndk build command is present in make file .
Should I run the make command after building Android Project or before building Android Project ?

**Comment by ashokbugude** [comment]
In the make file, only ndk-build is executed , the other commands ndk-install and and ndk-clean-build are not being executed

**Comment by sladomic** [comment]
you mean even if you try "make clean" or "make install"?

**Comment by ashokbugude** [comment]
Sorry , I thought all the 3 commands would be executed 1 after another by ruuning  'make -f Makefile'
I need to run below 3 commands one after other right ?
1. make -f Makefile clean
2. make -f Makefile build
3. make -f Makefile install

**Comment by sladomic** [comment]
exactly..I usually run:
make clean
make
make install

**Comment by ashokbugude** [comment]
Thanks
