### ISSUE TITLE
Add Person and Recognition with 'custom images/video' instead of camera 

### ISSUE THREAD

**Issue by ashokbugude** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#26]
Hi

I have set of images which needs to trained for which I need to provide these as input to 'Add Person'
Currently its using camera Frames

I also have a set of images which needs to be recognized of training.
Currently its using camera Frames 

Is there any way we can achieve the above task in this app, ie using custom images for training and recognition instead of using camera frames

**Comment by sladomic** [comment]
Hi @ashokbugude 

You can just work with the folders in /sdcard/Pictures/facerecognition/training

1. Add a unique folder name
2. Paste face images into it

The images, where the face cannot be detected will be skipped. So if you add for example 20 images, but the face can only be detected in 15 of them, only 15 images will be used for training.

The same can be done for recognition, if you use the Test function and add test images to the folder sdcard/Pictures/facerecognition/test

Regards,
Michael

**Comment by ashokbugude** [comment]
Hi Michael,

Thanks for your response,
Could you please clarify a doubt of mine.

When we use camera for detecting/Add Person, the new folder get created in '/sdcard/Pictures/facerecognition/training' with **cropped** images of faces

But

When I create folders manually , the images are **not cropped with faces**
So when I do the training at this point of time, would the training be done for entire image ?
OR
Face if detected from the uncropped images be cropped automatically and then used for training ?

Would it give the same results in both cases ?

Regards
Ashok

**Comment by sladomic** [comment]
It will try to detect the face in the uncropped image amd if detected use only the cropped image.

The results should be the same but it will be a bit slower due to the bigger images.

However you could save the images after cropping with the Filehelper function as done for debugging purposes (similar to /sdcard/Pictures/facerecognition/data/preprocessedImage.png)

**Comment by ashokbugude** [comment]
Thanks for the response

Can I please know the difference between reference and deviation folders in test folder ?
Should I place the custom images for testing in reference or deviation folder ?

**Comment by sladomic** [comment]
@ashokbugude the names are a bit strange but you can just use one folder and place all the images into the **reference** folder

I think we will remove this in a future version or implement a cross validation and test folder instead

**Comment by ashokbugude** [comment]
@sladomic Thanks for your response,

I ran the recognition test , it completed and displayed 95% as message.
I got the results in results folder with text files

One of the lines in text file says key_maximun_camera_view_width:320 and  key_maximun_camera_view_height:240 

Does it mean if the dimensions of image width > 320 or  key_maximun_camera_view_height > 240 , the other part of the image won't be used for recognition ?
If so how do we modify the parameter ?
Do we need to keep in mind of image dimensions while providing the custom as inputs ? 

Also does the results file print more than 1 persons names if it detects more than 1 person in an image ?

**Comment by sladomic** [comment]
Hi @ashokbugude 

key_maximun_camera_view_width and key_maximun_camera_view_height have no effect for the Training or Test functions (only for Add Person and Recognition)

Do we need to keep in mind of image dimensions while providing the custom as inputs?
- Yes, the images should ideally be bigger than N x N, since you will detect a face in it, crop the image and resize it to N x N (in the preprocessing recognition). So if the image is already very small (e.g. 150 x 150) and the face is only 40 x 40 but you resize it to 160 x 160, you loose a lot of information

Also does the results file print more than 1 persons names if it detects more than 1 person in an image ?
- If more than 1 person is detected in the image, this image is skipped (_if (images == null || images.size() > 1)_)

**Comment by ashokbugude** [comment]
@sladomic Thanks for your response.

I found few issues while detecting face from custom images and from camera source as well.

Face is not detected from image if 
1. The face is tilted slightly sidewards or upwards/downwards
2. Camera is put at an angle (other than parallel) from the face
3. The distance between camera and face is more than 'one arm' distance.

Can I please know how can these issues be resolved

**Comment by sladomic** [comment]
Hi @ashokbugude 

There are several ways of improving the detection, but you need to keep in mind, that for example for Eigenfaces the face should be frontal and aligned to get the best results.

That's why we eliminate a lot of images, where we are not 100% sure, that the face is frontal aligned:

- Eliminate image if more than 1 face has been detected
- Eliminate image if the left eye couldn't be detected in the right half (and vice-versa)

The Viola-Jones algorithm, which is used here (OpenCV detectMultiScale function with Haar classifier) is of course a very old algorithm. More recent algorithms detect faces in every angle and then use face alignment to transfer the angled face into a frontal face. The scope of our work was face recognition, that's the reason we didn't focus on improving face detection.

To answer your questions:

1. If you disable eye detection, it detects more faces, but then the image cannot be eye aligned
2. Similar to 1.
3. Try to play with the parameters of the detection https://stackoverflow.com/a/20805153

**Comment by ashokbugude** [comment]
Thanks , I shall try the above ways

I am using TensorFlow algorithm (100 % accuracy one )
The need was actually to resolve the above 3 issues for recognition. Sorry for using the word detection earlier

If we train images with frontal face only as it's existing now, it's not recognizing 'angular camera' , 'tilted face' and 'face at a distance'.
For these 3 things to get recognized , do we need to do training of images with angular camera' , 'tilted face' and face at a distance?  
So if we improve the detection ,does it improve the recognition as well OR are there any other ways to improve the recognition irrespective of whatever the detection(frontal currently) may be,
